name: "Feature Request"
description: Create a new ticket for a new feature request
title: "[REQUEST]: "
labels: ["enhancement", "triage"]

body:
  - type: textarea
    id: Description
    attributes:
      label: "Description"
      description: Why do you want this sweet new feature and what does it address?
      placeholder: Tell us all about it!
    validations:
      required: true
